server {
    listen 80;
    listen [::]:80;
    server_name softkoredigital.co.za www.softkoredigital.co.za 128.140.50.160;

    root /var/www/softkoredigital;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
