server {
    listen 80;
    listen [::]:80;
    server_name softkoredigital.co.za;

    return 301 https://www.softkoredigital.co.za$request_uri;
}

server {
    listen 80;
    listen [::]:80;
    server_name www.softkoredigital.co.za 128.140.50.160;

    root /var/www/softkoredigital/out;
    index index.html;

    include /etc/nginx/snippets/softkore-redirects.conf;

    location / {
        try_files $uri $uri/ =404;
    }
}
